### ISSUE TITLE
[FEATURE] Create ADO pipeline for generating pypi package

### ISSUE THREAD

**Issue by miguelgfierro** [microsoft/recommenders#1408]
### Description

Andreas:
- [x] Remove the sys path include
- [x] Change the [current pipeline](https://github.com/microsoft/recommenders/tree/main/tests/ci/azure_pipeline_test) so it installs the package locally, instead of using the path
- [x] Update setup.py
- [x] Fix issue with spark tests
- [x] Fix the issue with GPU version to match TF 1.15
- [x] Update documentation to reflect the new installation process
- [x] Review docs evaluation and datasets
- [x] test if the wheel package works on Databricks

Miguel:
- [x] Add a new yaml file that when [there is a new tag](https://github.com/microsoft/LightGBM/blob/master/.vsts-ci.yml#L5), builds a package with bdist, installs it, executes all tests (unit, smoke and integration) 
- [x] Create the github release draft
- [x] Upload artifacts to the github release draft: wheel and compressed code
- [x] Publish the wheel to the package limbo only when we are executing a release
- [x] Add fix to the spark tests in the pipeline
- [x] BUG: remove the wildcard in the installation and use the full name programmatically [see comment](https://github.com/microsoft/recommenders/issues/1408#issuecomment-848898749)
- [x] Check why we are installing all the deps in CPU, instead of only the CPU ones [see run](https://dev.azure.com/best-practices/recommenders/_build/results?buildId=47347&view=logs&j=ea6d793f-c9bd-55e6-b1b2-e25bd3674a1c&t=58ebb881-49a2-5c8f-c3f1-1abae14a2a25)
- [x] Make sure we are using the package when running the tests, [see comment here](https://github.com/microsoft/recommenders/issues/1408#issuecomment-850351697)
- [x] Fix issue with xlearn, it was using gpu deps that were not needed
- [x] See if we can simplify the code when forcing exit on error by removing exit -1 on each line and add other instructions. See [comment](https://github.com/microsoft/recommenders/issues/1408#issuecomment-850391727)
- [x] if smoke tests fail, we don't continue with the integration tests (nice to have feature). [Working now](https://dev.azure.com/best-practices/recommenders/_build/results?buildId=47475&view=logs&j=b097bf04-c10b-513d-2c77-b9ddcc54001a&t=2a7f1c25-fa3f-589c-0e5d-3acbe763a1a5)
- [ ] Review docs common, reco, tuning:
    - [x] common
    - [ ] recommender
    - [ ] tunning
- [x] Do a dry run with all the tests (it will take >8h) [run worked on 3/6/2021](https://dev.azure.com/best-practices/recommenders/_build/results?buildId=47506&view=results)
- [x] Fix deeprec unit tests
- [x] Analyze flaky tests and see if backoff lib can help (nice to have feature)
- [x] Create a tag and check that all tests pass (it will take >8h)
- [x] Check why automatic commit gives an error and manual trigger does not. [See comment here](https://github.com/microsoft/recommenders/pull/1427#issuecomment-855974570)
- [x] test if the wheel package works on Synapse -> if we upload the wheel to Synapse pool, it installs the core deps
- [ ] Check if we can install extra deps (like spark or GPU) if we do pip install in the pool runtime
- [ ] Reduce the time of the GPU smoke tests [see details](https://github.com/microsoft/recommenders/issues/1408#issuecomment-846933384)
- [ ] Automatically add the tag name to the draft release (nice to have feature)

Yan
- [ ] Update the documentation to make sure it reflects the latest code changes, see issue https://github.com/microsoft/recommenders/issues/942
- [ ] Update docs/README.md
- [ ] automatically build the documentation on 3 environments: latest (main branch), staging and stable (latest tag) using https://readthedocs.org/projects/microsoft-recommenders/

**Comment by miguelgfierro** [comment]
Issue with NNI int he nightly CPU tests:
```
=================================== FAILURES ===================================
_____________________________ test_nni_tuning_svd ______________________________

notebooks = {'als_deep_dive': '/home/recocat/myagent/_work/8/s/examples/02_model_collaborative_filtering/als_deep_dive.ipynb', 'al...p_dive': '/home/recocat/myagent/_work/8/s/examples/02_model_collaborative_filtering/cornac_bivae_deep_dive.ipynb', ...}
output_notebook = 'output.ipynb', kernel_name = 'python3'
tmp = '/tmp/pytest-of-recocat/pytest-17/tmpata1p8g8'

    @pytest.mark.integration
    @pytest.mark.skipif(sys.platform == "win32", reason="nni not installable on windows")
    def test_nni_tuning_svd(notebooks, output_notebook, kernel_name, tmp):
        notebook_path = notebooks["nni_tuning_svd"]
        pm.execute_notebook(
            notebook_path,
            output_notebook,
            kernel_name=kernel_name,
            parameters=dict(
                MOVIELENS_DATA_SIZE="100k",
                SURPRISE_READER="ml-100k",
                TMP_DIR=tmp,
                MAX_TRIAL_NUM=1,
                NUM_EPOCHS=1,
                WAITING_TIME=20,
>               MAX_RETRIES=50,
            ),
        )

tests/integration/examples/test_notebooks_python.py:185: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/anaconda/envs/nightly_linux_cpu/lib/python3.6/site-packages/papermill/execute.py:122: in execute_notebook
    raise_for_execution_errors(nb, output_path)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

nb = {'cells': [{'id': '9b218528', 'cell_type': 'markdown', 'source': '<span style="color:red; font-family:Helvetica Neue, ...end_time': '2021-05-23T13:21:49.650227', 'duration': 4.767072, 'exception': True}}, 'nbformat': 4, 'nbformat_minor': 5}
output_path = 'output.ipynb'

    def raise_for_execution_errors(nb, output_path):
        """Assigned parameters into the appropriate place in the input notebook
    
        Parameters

```

**Comment by miguelgfierro** [comment]
issue when executing the spark tests:
```

E               211         # data via a socket.
E               212         # scala's mangled names w/ $ in them require special treatment.
E           --> 213         self._encryption_enabled = self._jvm.PythonUtils.getEncryptionEnabled(self._jsc)
E               214 
E               215         self.pythonExec = os.environ.get("PYSPARK_PYTHON", 'python')
E           
E           /anaconda/envs/nightly_linux_spark/lib/python3.6/site-packages/py4j/java_gateway.py in __getattr__(self, name)
E              1485         else:
E              1486             raise Py4JError(
E           -> 1487                 "{0}.{1} does not exist in the JVM".format(self._fqn, name))
E              1488 
E              1489     def _get_args(self, args):
E           
E           Py4JError: org.apache.spark.api.python.PythonUtils.getEncryptionEnabled does not exist in the JVM

```

**Comment by miguelgfierro** [comment]
issue when executing the GPU tests, it takes longer that 3h:
the smoke tests:
```
============================== slowest durations ===============================
421.27s call     tests/smoke/examples/test_notebooks_gpu.py::test_naml_smoke
310.33s call     tests/smoke/examples/test_notebooks_gpu.py::test_npa_smoke
290.89s call     tests/smoke/reco_utils/recommender/test_deeprec_model.py::test_model_slirec
272.22s call     tests/smoke/reco_utils/recommender/test_newsrec_model.py::test_model_naml
180.76s call     tests/smoke/examples/test_notebooks_gpu.py::test_lstur_smoke
159.12s call     tests/smoke/examples/test_notebooks_gpu.py::test_nrms_smoke
142.98s call     tests/smoke/reco_utils/recommender/test_newsrec_model.py::test_model_npa
142.75s call     tests/smoke/reco_utils/recommender/test_newsrec_model.py::test_model_lstur
125.09s call     tests/smoke/reco_utils/recommender/test_newsrec_model.py::test_model_nrms
101.21s call     tests/smoke/examples/test_notebooks_gpu.py::test_ncf_deep_dive_smoke
94.41s call     tests/smoke/examples/test_notebooks_gpu.py::test_wide_deep_smoke
61.39s call     tests/smoke/examples/test_notebooks_gpu.py::test_xdeepfm_smoke
57.54s call     tests/smoke/examples/test_notebooks_gpu.py::test_cornac_bivae_smoke
40.61s call     tests/smoke/examples/test_notebooks_gpu.py::test_ncf_smoke
30.62s call     tests/smoke/examples/test_notebooks_gpu.py::test_fastai_smoke
22.85s call     tests/smoke/reco_utils/recommender/test_deeprec_model.py::test_model_dkn
19.03s call     tests/smoke/reco_utils/recommender/test_deeprec_model.py::test_model_sum
6.87s call     tests/smoke/reco_utils/recommender/test_deeprec_model.py::test_model_lightgcn
4.46s call     tests/smoke/reco_utils/recommender/test_newsrec_utils.py::test_naml_iterator
2.92s call     tests/smoke/reco_utils/recommender/test_newsrec_utils.py::test_news_iterator
2.77s call     tests/smoke/reco_utils/recommender/test_deeprec_utils.py::test_DKN_iterator
2.50s call     tests/smoke/reco_utils/recommender/test_deeprec_model.py::test_model_xdeepfm
0.60s call     tests/smoke/reco_utils/recommender/test_deeprec_model.py::test_FFM_iterator
0.21s call     tests/smoke/reco_utils/recommender/test_deeprec_utils.py::test_Sequential_Iterator
0.03s call     tests/smoke/examples/test_notebooks_gpu.py::test_gpu_vm
0.01s teardown tests/smoke/examples/test_notebooks_gpu.py::test_wide_deep_smoke

```

**Comment by miguelgfierro** [comment]
trying to mv package from one job to another, see this log: https://dev.azure.com/best-practices/recommenders/_build/results?buildId=47278&view=logs&j=1d2f55de-c984-5e06-0d18-75388f298a89&t=085f7f2b-f470-5c05-ab6d-e7d0f29f99ca

from unit test:
```
216	/home/recocat/myagent/_work/9/a/binaries/reco_utils-0.5.1-py3-none-any.whl
220	/home/recocat/myagent/_work/9/a/binaries
224	/home/recocat/myagent/_work/9/a
```

from Package job:
```
  --- LIST OF ARTIFACTS ---
Artifact folder: /home/recocat/myagent/_work/9/a
1988	/home/recocat/myagent/_work/9/a/archives/Recommenders-example_notebooks.zip
236	/home/recocat/myagent/_work/9/a/archives/Recommenders-reco_utils_code.zip
168	/home/recocat/myagent/_work/9/a/archives/Recommenders-reco_utils_code.tar.gz
1940	/home/recocat/myagent/_work/9/a/archives/Recommenders-example_notebooks.tar.gz
4336	/home/recocat/myagent/_work/9/a/archives
4340	/home/recocat/myagent/_work/9/a
```

**Comment by anargyri** [comment]
Is this folder cleaned up by any command in the script perhaps after the pip install?

**Comment by anargyri** [comment]
Here is what I think is the complete setup for a brand new DSVM.
	
cd /dsvm/tools/spark/
sudo wget https://mirrors.ukfast.co.uk/sites/ftp.apache.org/spark/spark-2.4.8/spark-2.4.8-bin-hadoop2.7.tgz 
sudo gunzip spark-2.4.8-bin-hadoop2.7.tgz
sudo tar xf spark-2.4.8-bin-hadoop2.7.tar
rm /dsvm/tools/spark/current
sudo ln -s /dsvm/tools/spark/spark-2.4.8-bin-hadoop2.7 /dsvm/tools/spark/current

conda deactivate
conda create -n reco python==3.7
conda activate reco
export PYSPARK_DRIVER_PYTHON=/anaconda/envs/reco/bin/python
export PYSPARK_PYTHON=/anaconda/envs/reco/bin/python
conda install cudatoolkit=10.0 'cudnn>=7.6'
	
Go to recommenders directory

python setup.py bdist_wheel
pip install dist/ms_recommenders-0.5.0-py3-none-any.whl[all]
pip install pytest
export PYTHONPATH=<recommenders directory path>

pytest tests/unit --ignore=tests/unit/reco_utils/recommender/test_surprise_utils.py --ignore=tests/unit/reco_utils/tuning/test_nni_utils.py --ignore=tests/unit/reco_utils/recommender/test_vowpal_wabbit.py  --deselect=tests/unit/examples/test_notebooks_python.py::test_surprise_deep_dive_runs  --deselect=tests/unit/examples/test_notebooks_python.py::test_vw_deep_dive_runs 

pytest tests/smoke --deselect=tests/smoke/examples/test_notebooks_python.py::test_surprise_svd_smoke --deselect=tests/smoke/examples/test_notebooks_python.py::test_vw_deep_dive_smoke

pytest tests/integration --deselect=tests/integration/examples/test_notebooks_python.py::test_surprise_svd_integration --deselect=tests/integration/examples/test_notebooks_python.py::test_vw_deep_dive_integration

**Comment by anargyri** [comment]
Deselecting the Surprise, NNI and VW tests is a bit of a ñapa but we will upgrade the versions of these and put them in [all] in the near future.

**Comment by miguelgfierro** [comment]
Need to change the way I install the wheel to the full name `ms_recommenders-0.5.1-py3-none-any.whl`:
```
        echo "   --- BUILDING PACKAGE ---"
        pip install setuptools wheel twine || exit -1
        python setup.py sdist bdist_wheel || exit -1
        echo "   --- INSTALLING WHEEL ---"
        pip install --user dist/ms_recommenders*.whl${{ parameters.pip_opts }} --force-reinstall || exit -1
```
I get the error:
```
WARNING: Requirement 'dist/ms_recommenders*.whl[examples]' looks like a filename, but the file does not exist
ERROR: ms_recommenders*.whl is not a valid wheel filename
```

**Comment by gramhagen** [comment]
why are we using exit -1 everywhere? won't these commands generate a valid exit code if they fail?

**Comment by miguelgfierro** [comment]
> why are we using exit -1 everywhere? won't these commands generate a valid exit code if they fail?

no it's the opposite, they generate an error if the code fails. That's what was missing before and the reason why the ADO pipeline was passing even though the code inside had an error

**Comment by miguelgfierro** [comment]
@anargyri we need to review this error here:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nni 1.5 requires scikit-learn<0.22,>=0.20, but you have scikit-learn 0.24.2 which is incompatible.
```
See [logs at the bottom](https://dev.azure.com/best-practices/recommenders/_build/results?buildId=47342&view=logs&j=ea6d793f-c9bd-55e6-b1b2-e25bd3674a1c&t=58ebb881-49a2-5c8f-c3f1-1abae14a2a25&l=1028)
it looks like nni is being installed o_o, any idea of what could be happening?

**Comment by anargyri** [comment]
> @anargyri we need to review this error here:
> 
> ```
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> nni 1.5 requires scikit-learn<0.22,>=0.20, but you have scikit-learn 0.24.2 which is incompatible.
> ```
> 
> See [logs at the bottom](https://dev.azure.com/best-practices/recommenders/_build/results?buildId=47342&view=logs&j=ea6d793f-c9bd-55e6-b1b2-e25bd3674a1c&t=58ebb881-49a2-5c8f-c3f1-1abae14a2a25&l=1028)
> it looks like nni is being installed o_o, any idea of what could be happening?

This should not happen (see https://github.com/microsoft/recommenders/blob/211e1ae98ecc140432c52030e21ca27730986e5e/setup.py#L83)
Maybe your conda env is not clean and inlcudes nni from before? Or it's not the pipeline branch?

**Comment by gramhagen** [comment]
> > why are we using exit -1 everywhere? won't these commands generate a valid exit code if they fail?
> 
> no it's the opposite, they generate an error if the code fails. That's what was missing before and the reason why the ADO pipeline was passing even though the code inside had an error

It should be easier to just change the script conditions instead of adding failbacks to every line of code.
Right now we have conditions that allow steps to continue on errors and to run even when previous steps have failed. What is the logic that you want for each one of the steps in the dsvm_linux_template.yml? (i.e. which ones should run if there are failures, should they stop immediately, etc.)

**Comment by miguelgfierro** [comment]
@gramhagen I think I understand what you mean, but I don't know a way of doing it other than adding `exit -1` or piping the commands. Do you know of another way?

**Comment by miguelgfierro** [comment]
I realized that we are not using the package when runing the tests, we are using the local path of reco_utils. During the test, I'm going to remove the folder, so there is no confusion. FYI @anargyri

**Comment by gramhagen** [comment]
> @gramhagen I think I understand what you mean, but I don't know a way of doing it other than adding `exit -1` or piping the commands. Do you know of another way?

there are two options that we can try
1. use `set -e` at the beginning of each script block where you want it to fail when an error occurs
2. add an additional task at the beginning to cause all subsequent script tasks to fail if an error occurs
```
      - bash:  echo "##vso[task.setvariable variable=shellopts]errexit"
        displayName: "Force exit on error (bash)"
```

**Comment by miguelgfierro** [comment]
I was trying xlearn, and I couldn't find an error when installing, see logs:

```
$ pytest tests/integration/examples/test_notebooks_python.py::test_xlearn_fm_integration
========================================================================= test session starts ==========================================================================
platform linux -- Python 3.6.13, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/hoaphumanoid/notebooks/repos/recommenders, configfile: pytest.ini
collected 1 item

tests/integration/examples/test_notebooks_python.py F                                                                                                            [100%]

E                 4 import scrapbook as sb
E                 5 from tempfile import TemporaryDirectory
E           ----> 6 import xlearn as xl
E                 7 from sklearn.metrics import roc_auc_score
E                 8 import numpy as np
E
E           ModuleNotFoundError: No module named 'xlearn'

/anaconda/envs/recommenders/lib/python3.6/site-packages/papermill/execute.py:234: PapermillExecutionError

$ cmake
-bash: /usr/local/bin/cmake: No such file or directory
$ pip install cmake xlearn
Collecting cmake
  Using cached cmake-3.20.2-py2.py3-none-manylinux1_x86_64.whl (19.4 MB)
Collecting xlearn
  Using cached xlearn-0.40a1-py3-none-any.whl
Installing collected packages: xlearn, cmake
Successfully installed cmake-3.20.2 xlearn-0.40a1
(recommenders) hoaphumanoid@migonzarecommenders:~/notebooks/repos/recommenders$ which cmake
/anaconda/envs/recommenders/bin/cmake
$ pytest tests/integration/examples/test_notebooks_python.py::test_xlearn_fm_integration
========================================================================= test session starts ==========================================================================
platform linux -- Python 3.6.13, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/hoaphumanoid/notebooks/repos/recommenders, configfile: pytest.ini
collected 1 item

tests/integration/examples/test_notebooks_python.py .                                                                                                            [100%]

=========================================================================== warnings summary ===========================================================================
../../../../../anaconda/envs/recommenders/lib/python3.6/site-packages/pyspark/cloudpickle.py:47
  /anaconda/envs/recommenders/lib/python3.6/site-packages/pyspark/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

tests/integration/examples/test_notebooks_python.py::test_xlearn_fm_integration
  /anaconda/envs/recommenders/lib/python3.6/site-packages/traitlets/config/configurable.py:73: DeprecationWarning: Passing unrecoginized arguments to super(PapermillNotebookClient).__init__(input_path='/home/hoaphumanoid/notebooks/repos/recommenders/examples/02_model_hybrid/fm_deep_dive.ipynb').
  object.__init__() takes no parameters
  This is deprecated in traitlets 4.2.This error will be raised in a future release of traitlets.
    super(Configurable, self).__init__(**kwargs)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
============================================================== 1 passed, 2 warnings in 268.58s (0:04:28) ===============================================================
```

@gramhagen did you see any error when you changed this?

**Comment by miguelgfierro** [comment]
1. Tried `echo "##vso[task.setvariable variable=shellopts]errexit"`, didn't work: https://dev.azure.com/best-practices/recommenders/_build/results?buildId=47449&view=logs&j=ea6d793f-c9bd-55e6-b1b2-e25bd3674a1c&t=6da75047-e1a9-5d04-2608-170d7afc750d

**Comment by gramhagen** [comment]
@anargyri, I believe we took this out of the core dependencies and moved it into experimental. 
I think it would be good to create an experimental pipeline to test this and vw. We should probably skip this test here and do the usually try/catch around the imports.

**Comment by gramhagen** [comment]
@miguelgfierro you might also want to set `failOnStderr: true` for that task if you want it to immediately stop running tests.
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops

**Comment by anargyri** [comment]
@miguelgfierro Yes, I also tried the test you did on a DSVM and it worked. However, it failed on another platform (I think it was AML VM or Databricks) and I had to install the cmake executable. And we have not tested this combination on Windows. 

In general, there are issues with `pip install cmake` + xlearn on some platforms. This is why, in SETUP.md, we recommend installing the cmake executable. This agrees with xlearn docs too https://xlearn-doc.readthedocs.io/en/latest/install/index.html ("No matter what way you choose, make sure that your OS has already installed GCC or Clang (with the support of C++ 11) and CMake").

This is the reason why currently xlearn is in [all] option but not in the minimal pip install. It is similar to [gpu] and [spark] options; it requires a pre-setup before the pip install.

**Comment by anargyri** [comment]
I checked some notes I've kept and Databricks was having problems installing xlearn:

java.lang.RuntimeException: ManagedLibraryInstallFailed: org.apache.spark.SparkException: Process List(/databricks/python/bin/pip, install, recommender-utils, --disable-pip-version-check) exited with code 1.   Failed building wheel for xlearn
Command "/databricks/python3/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-mkzajzic/xlearn/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-8x4aiidp/install-record.txt --single-version-externally-managed --compile --install-headers /databricks/python3/include/site/python3.7/xlearn" failed with error code 1 in /tmp/pip-install-mkzajzic/xlearn/
 for library:PythonPyPiPkgId(recommender-utils,None,None,List()),isSharedLibrary=false

**Comment by anargyri** [comment]
Update: installing cmake and xlearn from pypi works on Databricks
![MicrosoftTeams-image (14)](https://user-images.githubusercontent.com/20682858/120477327-8b5ac780-c3a3-11eb-9c35-4d45829e76f8.png)

**Comment by anargyri** [comment]
It fails on Windows.

pip install cmake
pip install xlearn

completes but when I open python and `import xlearn` I get this error

   File "<stdin>", line 1, in <module>
  File "C:\Users\anargyri\.conda\envs\foo\lib\site-packages\xlearn\__init__.py", line 18, in <module>
    from .xlearn import *
  File "C:\Users\anargyri\.conda\envs\foo\lib\site-packages\xlearn\xlearn.py", line 19, in <module>
    from .base import _LIB, XLearnHandle
  File "C:\Users\anargyri\.conda\envs\foo\lib\site-packages\xlearn\base.py", line 34, in <module>
    _LIB = _load_lib()
  File "C:\Users\anargyri\.conda\envs\foo\lib\site-packages\xlearn\base.py", line 27, in _load_lib
    lib_path = find_lib_path()
  File "C:\Users\anargyri\.conda\envs\foo\lib\site-packages\xlearn\libpath.py", line 59, in find_lib_path
    'Cannot find xlearn Library in the candidate path'

**Comment by anargyri** [comment]
In any case, the above is not the recommended way to install xlearn on Windows, see
https://xlearn-doc.readthedocs.io/en/latest/install/install_windows.html
